# This workflow will build the library.
on: [push]

env:
  NODE_VERSION: '12.x'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Build Library
      run: |
        # Build and test the project, then
        # deploy to Azure Web App.
        npm install
        npm run all
        npm run test --if-present
